[package]
name = "wmt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.90"
crossterm = "0.28.1"
ratatui = { version = "0.29.0", features = ["unstable-widget-ref"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
